# Generated by Django 2.0.2 on 2018-12-18 02:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0003_board_junle'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='名無し', max_length=10, verbose_name='お名前')),
                ('text', models.TextField(verbose_name='本文')),
                ('board', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='board.Board', verbose_name='スレッド')),
            ],
        ),
    ]
